"""empty message

Revision ID: 2df61494ffad
Revises: 686d5bfdd54a
Create Date: 2020-05-23 10:53:07.449672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2df61494ffad'
down_revision = '686d5bfdd54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelearns',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('time_all', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('time_id')
    )
    op.add_column('goals', sa.Column('goal_cod', sa.String(length=15), nullable=False))
    op.create_unique_constraint(None, 'goals', ['goal_cod'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='unique')
    op.drop_column('goals', 'goal_cod')
    op.drop_table('timelearns')
    # ### end Alembic commands ###
