"""empty message

Revision ID: 32862dcea0bd
Revises: 8ecd1812124f
Create Date: 2020-05-23 18:40:42.099477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32862dcea0bd'
down_revision = '8ecd1812124f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('teachers_goals')
    op.drop_table('teachers')
    op.drop_table('goals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.INTEGER(), server_default=sa.text("nextval('goals_goal_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('goal_cod', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('goal_id', name='goals_pkey'),
    sa.UniqueConstraint('goal_cod', name='goals_goal_cod_key'),
    sa.UniqueConstraint('goal_name', name='goals_goal_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.INTEGER(), server_default=sa.text("nextval('teachers_teacher_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('picture', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('teacher_id', name='teachers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('teachers_goals',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], name='teachers_goals_goal_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name='teachers_goals_teacher_id_fkey')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_ditails', sa.VARCHAR(length=230), autoincrement=False, nullable=False),
    sa.Column('week_day', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('lesson_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('client_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('booking_id', name='bookings_pkey')
    )
    # ### end Alembic commands ###
