"""empty message

Revision ID: 3ce4dac0c27d
Revises: 78718c729667
Create Date: 2020-05-23 16:48:26.876022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce4dac0c27d'
down_revision = '78718c729667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachers_booking_id_fkey', 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'booking_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teachers_booking_id_fkey', 'teachers', 'bookings', ['booking_id'], ['booking_id'])
    # ### end Alembic commands ###
