"""empty message

Revision ID: 78718c729667
Revises: 2df61494ffad
Create Date: 2020-05-23 16:32:07.433254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78718c729667'
down_revision = '2df61494ffad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_goals')
    op.drop_table('public.clients')
    op.add_column('bookings', sa.Column('booking_ditails', sa.String(length=230), nullable=False))
    op.drop_constraint('bookings_teacher_id_fkey', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'teacher_id')
    op.add_column('reqforms', sa.Column('goal_name', sa.String(length=35), nullable=True))
    op.drop_constraint('reqforms_goal_id_fkey', 'reqforms', type_='foreignkey')
    op.drop_column('reqforms', 'goal_id')
    op.add_column('teachers', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'bookings', ['booking_id'], ['booking_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'booking_id')
    op.add_column('reqforms', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reqforms_goal_id_fkey', 'reqforms', 'goals', ['goal_id'], ['goal_id'])
    op.drop_column('reqforms', 'goal_name')
    op.add_column('bookings', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bookings_teacher_id_fkey', 'bookings', 'teachers', ['teacher_id'], ['teacher_id'])
    op.drop_column('bookings', 'booking_ditails')
    op.create_table('public.clients',
    sa.Column('client_id', sa.INTEGER(), server_default=sa.text('nextval(\'"public.clients_client_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('client_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('client_id', name='public.clients_pkey')
    )
    op.create_table('teachers_goals',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], name='teachers_goals_goal_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name='teachers_goals_teacher_id_fkey')
    )
    # ### end Alembic commands ###
